### ISSUE TITLE
Move elkgraph-to-sprotty to a separate reusable package

### ISSUE THREAD

**Issue by mingfang** [kieler/elkgraph-web#11]
I would like to use https://github.com/OpenKieler/elkgraph-web/blob/master/client/src/json/elkgraph-to-sprotty.ts on my own project.  Please make it a reusable npm package.

**Comment by mingfang** [comment]
Thanks to this project I was able to create a command line tool to generate diagram SVG files such the one on this page https://github.com/mingfang/terraform-provider-k8s/tree/master/modules/mysql.
I would like to open source my code but I need several of the files from this project.  I suppose I can cut and paste.

**Comment by uruuru** [comment]
@spoenemann is there something in the sprotty-layout project by now?

**Comment by spoenemann** [comment]
[sprotty-elk](https://github.com/eclipse/sprotty-layout/blob/master/sprotty-elk/src/elk-layout.ts) can transform a Sprotty graph to an ELK graph, but not the other way around.

**Comment by uruuru** [comment]
Ah, ok. 
Still, @mingfang if I understood you correctly, you simply copied the files by now (which is totally fine given the license)? I feel the piece of code is too small to justify its own package.
